citas/src/Entity/Citas.php
<?php

namespace App\Entity;

use App\Repository\CitasRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CitasRepository::class)]
class Citas
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $medico = null;

    #[ORM\Column(length: 255)]
    private ?string $paciente = null;

    #[ORM\Column]
    private ?int $identificacion = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fecha_cita = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMedico(): ?string
    {
        return $this->medico;
    }

    public function setMedico(string $medico): static
    {
        $this->medico = $medico;

        return $this;
    }

    public function getPaciente(): ?string
    {
        return $this->paciente;
    }

    public function setPaciente(string $paciente): static
    {
        $this->paciente = $paciente;

        return $this;
    }

    public function getIdentificacion(): ?int
    {
        return $this->identificacion;
    }

    public function setIdentificacion(int $identificacion): static
    {
        $this->identificacion = $identificacion;

        return $this;
    }

    public function getFechaCita(): ?\DateTimeInterface
    {
        return $this->fecha_cita;
    }

    public function setFechaCita(\DateTimeInterface $fecha_cita): static
    {
        $this->fecha_cita = $fecha_cita;

        return $this;
    }
}

citas/src/Form/CitasType.php
<?php

namespace App\Form;

use App\Entity\Citas;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CitasType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('medico')
            ->add('paciente')
            ->add('identificacion')
            ->add('fecha_cita')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Citas::class,
        ]);
    }
}

citas/src/Controller/CitasController.php
<?php

namespace App\Controller;

use App\Entity\Citas;
use App\Form\CitasType;
use App\Repository\CitasRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/citas')]
class CitasController extends AbstractController
{
    #[Route('/', name: 'app_citas_index', methods: ['GET'])]
    public function index(CitasRepository $citasRepository): Response
    {
        return $this->render('citas/index.html.twig', [
            'citas' => $citasRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_citas_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $cita = new Citas();
        $form = $this->createForm(CitasType::class, $cita);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($cita);
            $entityManager->flush();

            return $this->redirectToRoute('app_citas_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('citas/new.html.twig', [
            'cita' => $cita,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_citas_show', methods: ['GET'])]
    public function show(Citas $cita): Response
    {
        return $this->render('citas/show.html.twig', [
            'cita' => $cita,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_citas_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Citas $cita, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CitasType::class, $cita);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_citas_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('citas/edit.html.twig', [
            'cita' => $cita,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_citas_delete', methods: ['POST'])]
    public function delete(Request $request, Citas $cita, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cita->getId(), $request->request->get('_token'))) {
            $entityManager->remove($cita);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_citas_index', [], Response::HTTP_SEE_OTHER);
    }
}

citas/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
        <script src="https://kit.fontawesome.com/76a9090d04.js" crossorigin="anonymous"></script>
        
        <link rel="stylesheet" href={{asset('css/app.css')}}/>

        
        <link
                    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
                    rel="stylesheet"
                    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
                    crossorigin="anonymous"
        />
            









    </head>

    <body>

        <nav
            class="navbar navbar-expand-sm"
        >
            <div class="container">
                <a class="navbar-brand" href="#">Navbar</a>
                <button
                    class="navbar-toggler d-lg-none"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#collapsibleNavId"
                    aria-controls="collapsibleNavId"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavId">
                    <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" href="#" aria-current="page"
                                >Home
                                <span class="visually-hidden">(current)</span></a
                            >
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a
                                class="nav-link dropdown-toggle"
                                href="#"
                                id="dropdownId"
                                data-bs-toggle="dropdown"
                                aria-haspopup="true"
                                aria-expanded="false"
                                >Dropdown</a
                            >
                            <div
                                class="dropdown-menu"
                                aria-labelledby="dropdownId"
                            >
                                <a class="dropdown-item" href="#"
                                    >Action 1</a
                                >
                                <a class="dropdown-item" href="#"
                                    >Action 2</a
                                >
                            </div>
                        </li>
                    </ul>
                    <form class="d-flex my-2 my-lg-0">
                        <input
                            class="form-control me-sm-2"
                            type="text"
                            placeholder="Buscar"
                        />
                        <button
                            class="btn btn-outline my-2 my-sm-0"
                            type="submit"
                        >
                            Buscar
                        </button>
                    </form>
                </div>
            </div>
        </nav>
        




        {% block body %}{% endblock %}
    </body>
</html>

citas/templates/citas/_delete_form.html.twig
<form method="post" action="{{ path('app_citas_delete', {'id': cita.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cita.id) }}">
    <button class="btn">Delete</button>
</form>

citas/templates/citas/_form.html.twig
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}

citas/templates/citas/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Citas{% endblock %}

{% block body %}
    <h1>Edit Citas</h1>




    {{ include('citas/_form.html.twig', {'button_label': 'Update'}) }}
    <a href="{{ path('app_citas_index') }}">back to list</a>

    {{ include('citas/_delete_form.html.twig') }}

{% endblock %}

citas/templates/citas/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Citas index{% endblock %}

{% block body %}
    <h1>Citas index</h1>
    <div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Medico</th>
                <th>Paciente</th>
                <th>Identificacion</th>
                <th>Fecha_cita</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for cita in citas %}
            <tr>
                <td>{{ cita.id }}</td>
                <td>{{ cita.medico }}</td>
                <td>{{ cita.paciente }}</td>
                <td>{{ cita.identificacion }}</td>
                <td>{{ cita.fechaCita ? cita.fechaCita|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a class="btn" href="{{ path('app_citas_show', {'id': cita.id}) }}"><i class="fa-solid fa-eye"></i></a>
                    <a class="btn" href="{{ path('app_citas_edit', {'id': cita.id}) }}"><i class="fa-solid fa-pen-to-square"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_citas_new') }}">Añadir</a>
    </div>
{% endblock %}

citas/templates/citas/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Citas{% endblock %}

{% block body %}
    <h1>Create new Citas</h1>

    {{ include('citas/_form.html.twig') }}

    <a href="{{ path('app_citas_index') }}">back to list</a>
{% endblock %}

citas/templates/citas/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Citas{% endblock %}

{% block body %}
    <h1>Citas</h1>
    
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ cita.id }}</td>
            </tr>
            <tr>
                <th>Medico</th>
                <td>{{ cita.medico }}</td>
            </tr>
            <tr>
                <th>Paciente</th>
                <td>{{ cita.paciente }}</td>
            </tr>
            <tr>
                <th>Identificacion</th>
                <td>{{ cita.identificacion }}</td>
            </tr>
            <tr>
                <th>Fecha_cita</th>
                <td>{{ cita.fechaCita ? cita.fechaCita|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_citas_index') }}">back to list</a>

    <a href="{{ path('app_citas_edit', {'id': cita.id}) }}">edit</a>

    {{ include('citas/_delete_form.html.twig') }}
    
{% endblock %}